version: "3.8"
services:
  colectivo:
    # Use a prebuilt image from registry; no build here.
    image: ${IMAGE:-ghcr.io/mauricioff2015/colectivo-web:latest}
    container_name: colectivo-web
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
