version: '3.8'

# NOTE:
# This compose builds the image locally and is intended for LOCAL development/build.
# Do NOT use this file directly in Portainer Stacks. Use docker-compose.portainer.yml instead,
# which pulls a prebuilt image from a registry.

services:
  colectivo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL}
    container_name: colectivo-web
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_BASE_URL=${API_BASE_URL}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend

networks:
  backend:
    external: true
    name: backend
